### ISSUE TITLE
yui3-custom-modules example error?

### ISSUE THREAD

**Issue by dormfood** [gotwarlost/ytestrunner#9]
Hi,

I installed ytestrunner and yui globally, and I try to run yui3-custom-modules example with
ytestrunner --yui3 --yconfig test/config.json
and it doesn't seem to work:

Error Log:
###### 

[details] Cannot read property 'Whisper' of undefined
[stack] TypeError: Cannot read property 'Whisper' of undefined
    at Object.YUI.add.requires [as fn](/usr/ytestrunner/examples/yui3-custom-modules/test/foo-test.js:6:24)
    at proto._attach (/usr/local/lib/node_modules/yui/yui-nodejs/yui-nodejs.js:775:37)
    at proto._use.handleLoader (/usr/local/lib/node_modules/yui/yui-nodejs/yui-nodejs.js:1112:33)
    at Object.YUI.add.Y.Loader._finish (/usr/local/lib/node_modules/yui/yui-nodejs/yui-nodejs.js:6701:19)
    at Object.YUI.add.Y.Loader._onFailure (/usr/local/lib/node_modules/yui/yui-nodejs/yui-nodejs.js:6795:14)
    at Object.YUI.add.Y.Loader._insert.complete (/usr/local/lib/node_modules/yui/yui-nodejs/yui-nodejs.js:6995:24)
    at YUI.add.Y.Loader._insert.Y.Get.js.onFailure (/usr/local/lib/node_modules/yui/yui-nodejs/yui-nodejs.js:7062:30)
    at YUI.add.fail (/usr/local/lib/node_modules/yui/yui-nodejs/yui-nodejs.js:3686:30)
    at YUI.add.Y.Get.js.execute (/usr/local/lib/node_modules/yui/yui-nodejs/yui-nodejs.js:3820:21)
    at Function.YUI.add.Y.Get._include (/usr/local/lib/node_modules/yui/yui-nodejs/yui-nodejs.js:3778:17)
runTests returned an error
Uncaught exception!
[details] Error starting tests:TypeError: Cannot read property 'Whisper' of undefined
[stack] Error: Error starting tests:TypeError: Cannot read property 'Whisper' of undefined
    at BaseTestRunner.runTests.mainFn (/usr/local/lib/node_modules/ytestrunner/lib/base-test-runner.js:139:37)
    at Yui3TestRunner.BaseTestRunner.runTests (/usr/local/lib/node_modules/ytestrunner/lib/base-test-runner.js:167:13)
    at mainFn (/usr/local/lib/node_modules/ytestrunner/lib/cli.js:313:28)
    at Object.next (/usr/local/lib/node_modules/ytestrunner/node_modules/fileset/lib/fileset.js:41:14)
    at Fileset.EventEmitter.emit (events.js:96:17)
    at Fileset.Glob._processEmitQueue (/usr/local/lib/node_modules/ytestrunner/node_modules/fileset/node_modules/glob/glob.js:280:10)
    at Fileset.Glob.emitMatch (/usr/local/lib/node_modules/ytestrunner/node_modules/fileset/node_modules/glob/glob.js:265:8)
    at Fileset.Glob._finish (/usr/local/lib/node_modules/ytestrunner/node_modules/fileset/node_modules/glob/glob.js:227:8)
    at Fileset.<anonymous> (/usr/local/lib/node_modules/ytestrunner/node_modules/fileset/node_modules/glob/glob.js:168:27)
    at Fileset.cb (/usr/local/lib/node_modules/ytestrunner/node_modules/fileset/node_modules/glob/glob.js:301:11)
###### 

Did I miss some other package to install?
Thanks,
Steven

**Comment by dormfood** [comment]
sorry. just saw issue 8.
